1# PALAVRA_RESERVADA | 1
1# IDENTIFICADOR | 0
2# PALAVRA_RESERVADA | 2
3# IDENTIFICADOR | 1
3# OPERADOR_DELIMITADOR | 44
3# IDENTIFICADOR | 2
3# OPERADOR_DELIMITADOR | 58
3# PALAVRA_RESERVADA | 3
4# PALAVRA_RESERVADA | 4
5# IDENTIFICADOR | 1
5# OPERADOR_DELIMITADOR | 5
5# NUM_INTEIRO | 10
6# IDENTIFICADOR | 2
6# OPERADOR_DELIMITADOR | 5
6# NUM_INTEIRO | 3
7# PALAVRA_RESERVADA | 5
7# OPERADOR_DELIMITADOR | 40
7# IDENTIFICADOR | 3
7# OPERADOR_DELIMITADOR | 44
7# IDENTIFICADOR | 1
7# OPERADOR_DELIMITADOR | 43
7# IDENTIFICADOR | 2
7# OPERADOR_DELIMITADOR | 41
8# PALAVRA_RESERVADA | 6
8# OPERADOR_DELIMITADOR | 40
8# IDENTIFICADOR | 4
8# OPERADOR_DELIMITADOR | 44
8# IDENTIFICADOR | 1
8# OPERADOR_DELIMITADOR | 42
8# IDENTIFICADOR | 2
8# OPERADOR_DELIMITADOR | 41
9# PALAVRA_RESERVADA | 7
9# OPERADOR_DELIMITADOR | 40
9# IDENTIFICADOR | 5
9# OPERADOR_DELIMITADOR | 44
9# IDENTIFICADOR | 1
9# OPERADOR_DELIMITADOR | 47
9# IDENTIFICADOR | 2
9# OPERADOR_DELIMITADOR | 41
10# PALAVRA_RESERVADA | 8
10# OPERADOR_DELIMITADOR | 40
10# IDENTIFICADOR | 6
10# OPERADOR_DELIMITADOR | 44
10# IDENTIFICADOR | 1
10# OPERADOR_DELIMITADOR | 92
10# IDENTIFICADOR | 2
10# OPERADOR_DELIMITADOR | 41
11# PALAVRA_RESERVADA | 9

=== TABELA DE SIMBOLOS ===
0 | CalculadoraBasica | linha 1
1 | n1 | linha 3
2 | n2 | linha 3
3 | Soma:  | linha 7
4 | Multiplicação:  | linha 8
5 | Divisão real (/):  | linha 9
6 | Divisão inteira (\):  | linha 10
